---

- name: Ensure Skynet's dependencies are installed.
  apt:
    state: present
    name:
      - python3
      - python3-pip
      - python3-dev
      - build-essential
      - python3-mysqldb
      - supervisor
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install Cement
  pip:
    name: cement
    state: present
    executable: pip3
  become: yes
