---

- name: Allow 'aegir' user to restart Skynet queue
  copy:
    dest: "/etc/sudoers.d/{{ aegir_user }}-skynet"
    content: |
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl start skynet-queue
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl stop skynet-queue
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl restart skynet-queue
    mode: 0440

- name: Add Skynet Supervisor config
  template:
    src: skynet-queue.conf.j2
    dest: /etc/supervisor/conf.d/skynet-queue.conf
  notify: Reload Supervisor

- name: Ensure that hosting-queued service is stopped and disabled.
  service:
    name: hosting-queued
    state: stopped
    enabled: no
  register: stop_queued

- name: Enable Skynet module
  include_role:
    name: consensus.aegir
    tasks_from: extra-module.yml
  vars:
    aegir_extra_module: hosting_skynet

- meta: flush_handlers

- name: Drain task queue in preparation of starting Skynet.
  shell: drush @hostmaster hosting-tasks #--force
  become: True
  become_user: "{{ aegir_user }}"
  when: stop_queued.changed

- name: Wait until the Skynet script is deployed.
  wait_for:
    path: "{{ aegir_root }}/config/skynet/skynet.py"

- name: Start Skynet via Supervisor
  supervisorctl:
    name: skynet-queue
    state: started
