---

- name: Ensure that hosting-queued service is stopped and disabled.
  service:
    name: hosting-queued
    state: stopped
    enabled: no
  become: yes

- name: Enable Skynet module
  include_role:
    name: consensus.aegir
    tasks_from: extra-module.yml
  vars:
    aegir_extra_module: hosting_skynet

- name: Ensure handlers don't run while the following tasks execute asyncronously.
  meta: flush_handlers

- name: Drain task queue in preparation of starting Skynet.
  shell: drush @hostmaster hosting-tasks
  become: yes
  become_user: "{{ aegir_user }}"
  when: (aegir_extra_module_enabled.rc is defined) and (aegir_extra_module_enabled.rc != 0)

- name: Verify the Aegir front-end to ensure Skynet config file is generated.
  shell: drush @hostmaster hosting-task @hostmaster verify && drush @hostmaster hosting-tasks
  become: yes
  become_user: "{{ aegir_user }}"
  when: (aegir_extra_module_enabled.rc is defined) and (aegir_extra_module_enabled.rc != 0)

- name: Wait until the Skynet script is deployed.
  wait_for:
    path: "{{ aegir_root }}/config/skynet/skynet.py"
  when: (aegir_extra_module_enabled.rc is defined) and (aegir_extra_module_enabled.rc != 0)

