---

- name: Ensure that hosting-queued service is stopped and disabled.
  service:
    name: hosting-queued
    state: stopped
    enabled: no

- name: Allow 'aegir' user to restart Skynet queue
  copy:
    dest: "/etc/sudoers.d/{{ aegir_user }}-skynet"
    content: |
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl start skynet-queue
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl stop skynet-queue
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl restart skynet-queue
    mode: 0440
  register: aegir_skynet_sudoers

- name: Enable Skynet module
  include_role:
    name: consensus.aegir
    tasks_from: extra-module.yml
  vars:
    aegir_extra_module: hosting_skynet

- name: Ensure handlers don't run while the following tasks execute asyncronously.
  meta: flush_handlers

- name: Drain task queue in preparation of starting Skynet.
  shell: drush @hostmaster hosting-tasks
  become: True
  become_user: "{{ aegir_user }}"
  when: aegir_extra_module_enabled.rc != 0

- name: Verify the Aegir front-end to ensure Skynet config file is generated.
  shell: drush @hostmaster hosting-task @hostmaster verify && drush @hostmaster hosting-tasks
  become: True
  become_user: "{{ aegir_user }}"
  when: aegir_extra_module_enabled.rc != 0

- name: Wait until the Skynet script is deployed.
  wait_for:
    path: "{{ aegir_root }}/config/skynet/skynet.py"
  when: aegir_extra_module_enabled.rc != 0

- name: Add Skynet Supervisor config
  template:
    src: skynet-queue.conf.j2
    dest: /etc/supervisor/conf.d/skynet-queue.conf
  register: skynet_supervisor_config

- name: Ensure Supervisor service is running
  service:
    name: supervisor
    enabled: yes
    state: started

- name: Reload Supervisor if config changed
  command: supervisorctl reload
  become: yes
  when: skynet_supervisor_config.changed |bool

- name: Start Skynet via Supervisor
  supervisorctl:
    name: skynet-queue
    state: started
