---

- name: Allow 'aegir' user to restart Skynet queue
  copy:
    dest: "/etc/sudoers.d/{{ aegir_user }}-skynet"
    content: |
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl start skynet-queue
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl stop skynet-queue
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl restart skynet-queue
    mode: 0440

- name: Add Skynet Supervisor config
  template:
    src: skynet-queue.conf.j2
    dest: /etc/supervisor/conf.d/skynet-queue.conf
  notify: Reload Supervisor

- name: Enable Skynet module
  include_role:
    name: consensus.aegir
    tasks_from: extra-module.yml
  vars:
    aegir_extra_module: hosting_skynet

- meta: flush_handlers

- name: Start Skynet via Supervisor
  supervisorctl:
    name: skynet-queue
    state: started
