---
- name: Ensure Supervisor service is running
  service:
    name: supervisor
    enabled: yes
    state: started
  become: yes

- name: Reload Supervisor if config changed
  command: supervisorctl reload
  become: yes
  when: skynet_supervisor_config.changed |bool

- name: Start Skynet via Supervisor
  supervisorctl:
    name: skynet-queue
    state: started
  become: yes
